# Generated by Django 2.0 on 2018-10-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmebase',
            name='nom',
            field=models.CharField(default='defaut', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
