# Generated by Django 2.0 on 2017-12-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoReceived',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('action', models.CharField(blank=True, max_length=30, null=True)),
                ('blockSpec', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(max_length=10)),
            ],
        ),
    ]
