# Generated by Django 2.0 on 2018-10-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0002_auto_20181025_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='time',
            field=models.BigIntegerField(),
        ),
    ]
