# Generated by Django 2.0 on 2017-12-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0002_inforeceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='inforeceived',
            name='block_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inforeceived',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
