# Generated by Django 2.0 on 2017-12-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0004_auto_20171212_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droppedblock',
            name='inputs',
        ),
        migrations.AddField(
            model_name='droppedblock',
            name='inputs',
            field=models.ManyToManyField(null=True, to='snap.Inputs'),
        ),
    ]
