# Generated by Django 2.0 on 2017-12-12 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snap', '0005_auto_20171212_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionprogrammation',
            name='user',
        ),
        migrations.AddField(
            model_name='actionprogrammation',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
