# Generated by Django 2.0 on 2017-12-12 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snap', '0006_auto_20171212_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionprogrammation',
            name='user',
        ),
        migrations.AddField(
            model_name='actionprogrammation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
