# Generated by Django 2.0 on 2017-12-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0007_auto_20171212_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='droppedblock',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.DroppedBlock'),
        ),
    ]
